env:
  browser: true
  es6: true
  node: true
extends: airbnb
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules:
  react/prop-types: off
  indent:
    - error
    - 2
    - ignoredNodes:
        - JSXElement
  comma-dangle: off
  no-unused-vars:
    - warn
    - argsIgnorePattern: ^res$|^req$|^next$|^_
  import/no-extraneous-dependencies: off
  consistent-return: off
  quotes:
    - error
    - single
    - avoidEscape: true
      allowTemplateLiterals: true
  no-underscore-dangle: off
  import/order: warn
  object-curly-spacing: warn
