env:
  browser: true
  es6: true
  node: true
extends: airbnb
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
  allowImportExportEverywhere: true
plugins:
  - react
  - react-hooks
rules:
  global-require: off
  arrow-parens: off
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
  react/jsx-filename-extension: off
  react/prop-types: off
  semi: never
  quotes: single
